theme: jekyll-theme-modernist
title: Smwhitaker4's CS499 Capstone Homepage.
description: This site was designed around demonstrating the enhancement progression for my console application called "Liar's Dice".
