// <auto-generated />
using System;
using LiarsDiceApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiarsDiceApi.Migrations
{
    [DbContext(typeof(LiarsDiceDbContext))]
    [Migration("20201130001042_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LiarsDiceApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DiceValueFive")
                        .HasColumnType("int");

                    b.Property<int>("DiceValueFour")
                        .HasColumnType("int");

                    b.Property<int>("DiceValueOne")
                        .HasColumnType("int");

                    b.Property<int>("DiceValueSix")
                        .HasColumnType("int");

                    b.Property<int>("DiceValueThree")
                        .HasColumnType("int");

                    b.Property<int>("DiceValueTwo")
                        .HasColumnType("int");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LiarsDiceApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("CalledLiar")
                        .HasColumnType("bit");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDiceGuess")
                        .HasColumnType("int");

                    b.Property<int>("ValueOfDieGuess")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId1");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LiarsDiceApi.Models.Game", b =>
                {
                    b.HasOne("LiarsDiceApi.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("LiarsDiceApi.Models.Player", b =>
                {
                    b.HasOne("LiarsDiceApi.Models.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameId1");
                });

            modelBuilder.Entity("LiarsDiceApi.Models.Game", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
